version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
      timezone: "UTC"